# Generated by Django 3.0.8 on 2020-07-17 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_tweetannotation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweetannotation',
            name='symptom',
            field=models.TextField(),
        ),
    ]
