# Generated by Django 3.0.8 on 2020-07-24 11:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20200717_1133'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='date',
            field=models.DateField(blank=True, default=datetime.date(2020, 7, 24)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tweet',
            name='tweet_id',
            field=models.TextField(blank=True),
        ),
    ]
